lab-2/graderManager/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "home#index"
  
  get "/home", to: "home#index"
  get "/catalog", to: "catalog#index"
end

lab-2/graderManager/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

lab-2/graderManager/app/models/course.rb
class Course < ApplicationRecord
end

lab-2/graderManager/app/models/section.rb
class Section < ApplicationRecord
end

lab-2/graderManager/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

lab-2/graderManager/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

lab-2/graderManager/app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
  def index
  end
end

lab-2/graderManager/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

lab-2/graderManager/app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def catalog
  end
end

lab-2/graderManager/app/helpers/application_helper.rb
module ApplicationHelper
end

lab-2/graderManager/app/helpers/catalog_helper.rb
module CatalogHelper
end

lab-2/graderManager/app/helpers/home_helper.rb
module HomeHelper
end

lab-2/graderManager/app/helpers/sections_helper.rb
module SectionsHelper
end

lab-2/graderManager/app/views/catalog/index.html.erb
<h1>This is the view for the catalog!!</h1>

<h1>Catalog#index</h1>
<p>Find me in app/views/catalog/index.html.erb</p>

lab-2/graderManager/app/views/home/index.html.erb
<div class="center jumbotron">
  <h1>This is the homepage for our grader manager</h1>

  <p>This view is app/views/home/index.html.erb</p>


<% if user_signed_in? %>

  
    <%= link_to "Browse Catalog", catalog_path, class: "btn btn-lg btn-primary" %>

    <%= link_to "Edit profile", edit_user_registration_path, class: "btn btn-lg btn-primary" %>

   <%= link_to "sign out", destroy_user_session_path, method: :get, class: "btn btn-lg btn-primary" %>

<% else %>
 
   <%= link_to "sign in", user_session_path, class: "btn btn-lg btn-primary" %>

   <%= link_to "sign up", new_user_registration_path, class: "btn btn-lg btn-primary"%>

<% end %>

lab-2/graderManager/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GraderManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

lab-2/graderManager/app/views/sections/catalog.html.erb
<h1>>This is the view for the catalog</h1>

<h1>Sections#catalog</h1>
<p>Find me in app/views/sections/catalog.html.erb</p>